const person = require('../controllers/person_controller')
const address=require('../controllers/address_controller')
const router =require('express').Router()
router.post('/addPerson',person.add)
router.get('/findperson/:id',person.findEmp)
router.get('/findaddr/:id',address.findRecord)
router.get('/findallRecords',person.findall)
router.get('/findRecords',address.findAllRecords)
router.put('/updaterecord/:id',person.updateRecord)
router.put('/updateaddressRecord/:id',address.updateAddress)
router.delete('/deleterecord/:id',person.deleteRecord)
router.delete('/deleteOneRecord/:id',address.deleteAddress)
router.post('/saveBulkData',person.bulkDataCreation)
router.put('/updateBulkPersonRecords',person.bulkUpdateRecords)
router.delete('/deleteBulkRecord',person.bulkDeleteRecords)
module.exports = router